### ISSUE TITLE
[Bug] If a character has multiple sources of persistent damage, Workbench's auto-damage only auto-applies the first one.

### ISSUE THREAD

**Issue by Malkyn99** [xdy/xdy-pf2e-workbench#686] opened 2023-03-05 21:27 UTC
Title. When a character had both persistent acid and fire damage, both were rolled at the end of their turn but only the first one rolled applied.

**Comment by xdy** [comment] 2023-03-11 09:05
Hmm. Works for me:
![image](https://user-images.githubusercontent.com/246024/224475533-a29f05a5-1bfd-428d-9716-aa0532d217ea.png)

**Comment by xdy** [comment] 2023-03-11 09:06
Closing issue, open another if you can reproduce it with no other modules and the latest version of the system.

**Closed as completed by xdy** 2023-03-11 09:06 UTC
