### ISSUE TITLE
Manifest URL of all versions are latest release

### ISSUE THREAD

**Issue by manfred7168** [xdy/xdy-pf2e-workbench#943] opened 2023-08-17 06:01 UTC
Too bad.
All Manifest URLs (Installation Links) in foundry always pointing to the latest release, so it's not possible to install a version of Workbench that runs with PF2e v5.2 (I know that it could be configured otherwise).
So I'm in need of an installation link for a workbench version compatible to PF2e v5.2 as we want to stay there and not taking Core Rules updates.

**Comment by xdy** [comment] 2023-12-29 17:16
Closing as duplicate of #932

**Closed as completed by xdy** 2023-12-29 17:16 UTC
