### ISSUE TITLE
Spell Mystifier Fails when selecting a spell variant

### ISSUE THREAD

**Issue by QwertTheWert** [xdy/xdy-pf2e-workbench#1111] opened 2023-11-19 07:07 UTC
When casting a spell that's hidden to the PC, selecting a variant of the spell makes the spell card visible. 
Additionally, the cast privately option also don't work when pressing the "cast" button on the character sheet. you have to click the spell icon on the char sheet for it to activate

**Comment by xdy** [comment] 2023-12-27 16:12
For now a workaround is to switch to Private GM roll before clicking the variant button.

**Comment by xdy** [comment] 2023-12-27 18:45
Closing as this is a duplicate of #1024

**Closed as completed by xdy** 2023-12-27 18:45 UTC
