### ISSUE TITLE
Recovery check works unexpectedly

### ISSUE THREAD

**Issue by krizzis** [xdy/xdy-pf2e-workbench#809] opened 2023-05-18 07:26 UTC
**Preconditions:** 
You need to activate option "... and add additional dying level(s) if taking damage when dying" in 'Manage world automation Settings" 

**Steps to reproduce:**
1. Get some character dying
2. Open character sheet and click 'Recovery check' button

**Expected result:** Dying value is not changed OR Dying value reduced in succesfull check
**Actual result:** Dying value increased with any result on roll

**Comment by xdy** [comment] 2023-05-18 08:09
I couldn't reproduce your exact problem but I did find a couple of bugs so this *may* be fixed in 4.71.1

**Comment by krizzis** [comment] 2023-05-18 11:46
Thanks for response. I've record a video. As you can see I'm using empty world with only workbech installed. All pf2e settings are default. May be it helps if you want to try again. Anyway thanks for you great job!

![Foundry_Virtual_Tabletop_fitTKhKYOL](https://github.com/xdy/xdy-pf2e-workbench/assets/13147187/60878057-d9c9-4445-b9b2-88b773cdd4d3)

**Comment by xdy** [comment] 2023-05-18 19:34
Yeah, that made it clearer. Reproduced and hopefully fixed. Give it another try using version 4.72.1 (all recovery-roll related settings have been reset to defaults so you need to turn those on again.)

**Closed as completed** 2023-05-21 14:31 UTC
