### ISSUE TITLE
[Bug] Character sheet skill actions / performance

### ISSUE THREAD

**Issue by roguedevjake** [xdy/xdy-pf2e-workbench#595] opened 2022-12-30 16:57 UTC
At the moment turning on character sheet skill actions introduces a lot of latency to various elements of PC sheets. 

Both to open them and when equipment is changed/added and effects added. 

I isolated it to the workbench module and further isolated it to the skill actions setting. 

impacts I have noticed are:
- ~1-2 second delay in opening a character sheet and skipping of 70ish percent of the fade animation.
- ~1 second delay in adding an item or adjusting the number of an item in the inventory.
- ~1-2 second delay and visible frame stutter on floating text when adding effects to a PC, becomes worse if the effect added adds a bunch of other effects at the same time.

May sound minor, but it introduces a fair bit of waiting to see if inputs actually worked or not, and fixing inputs. And the alchemist was over the moon to find out that his character no longer locked up for half a minute when preparing items for the day. 

(It was easily fixed for me by disabling them and forcing the setting on all players, the new skill action macro fills its use case for me anyway, but figured it was worth mentioning.)

**Comment by xdy** [comment] 2022-12-30 17:06
Yeah, I noticed that some time ago: https://discord.com/channels/880968862240239708/880969241552113695/1043222445076795392
Unfortunately I *still* haven't gotten around to taking a look at it. I'll put out a release tonight that at least notes that enabling them is likely to make sheets *very* slow.

**Comment by xdy** [comment] 2023-01-08 10:18
Turned out this was caused by a pf2e system change, and Supe fixed the root cause in the latest pf2e system release, so closing this issue. I'll remove the note about skill actions being slow, but won't do a separate release for just that.

**Closed as completed by xdy** 2023-01-08 10:18 UTC
Labels: bug, skill-actions
