### ISSUE TITLE
Reminder Considers Eidolons to be "Dead" and Issues a Warning

### ISSUE THREAD

**Issue by Armandeus66** [xdy/xdy-pf2e-workbench#380] opened 2022-08-20 06:20 UTC
PF2E Workbench has a reminder (first one) that you can check to give a blue banner warning if a token with 0 HP (and other reasons) tries to make an attack. It triggers for eidolons, which by system default have no HP because they share the summoner's. The banner doesn't stop the attack. I can disable it, but since summoners are part of the default system, perhaps the module should consider not counting 0 HP eidolons as "dead."

**Comment by xdy** [comment] 2022-08-27 20:20
Can't reproduce on the upcoming Workbench 4.0.0 release (which will be out after pf2e releases it's 4.0.0 version), so closing issue.
Make a new issue with more details if it still happens for you in 4.0.0

**Closed as completed by xdy** 2022-08-27 20:20 UTC
